# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:30
from __future__ import unicode_literals

import cementerio.models.terreno
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('fecha_regitro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Difunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, default=None, null=True)),
                ('fecha_fallecimiento', models.DateField(blank=True, default=None, null=True)),
                ('fecha_regitro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TR', 'Terreno regular'), ('GF', 'Gaveta Familiar')], default='TR', max_length=2)),
                ('capacidad', models.PositiveIntegerField(default=2)),
                ('manzana', models.CharField(max_length=10)),
                ('columna', models.PositiveIntegerField()),
                ('lote', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendido', models.BooleanField(default=True)),
                ('perpetuidad', models.BooleanField(default=False)),
                ('beneficiario', models.CharField(default=None, max_length=200, null=True)),
                ('recibo_pago', models.FileField(default=None, null=True, upload_to=cementerio.models.terreno.recibo_pago_path)),
                ('fecha_regitro', models.DateTimeField(auto_now_add=True)),
                ('fecha_venta', models.DateField(default=None, null=True)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrenos', to='cementerio.Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='difunto',
            name='terreno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='difuntos', to='cementerio.Terreno'),
        ),
    ]
