# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0004_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
