# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0006_auto_20170901_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ultimo_movimiento',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
