# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0007_auto_20171120_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='recibo_pago',
        ),
        migrations.AlterField(
            model_name='terreno',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='recibo_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
