# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0008_auto_20180702_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difunto',
            name='terreno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='difuntos', to='cementerio.Terreno'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='cementerio.Cliente'),
        ),
    ]
