# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-22 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0011_auto_20200422_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='manzana',
            field=models.CharField(max_length=20),
        ),
    ]
