# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-24 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0013_auto_20200422_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notas'),
        ),
    ]
