# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='recibo_numero',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
