# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0002_terreno_recibo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_movimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
