# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-04 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0009_auto_20180702_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difunto',
            name='fecha_nacimiento',
        ),
    ]
