# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-22 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0010_remove_difunto_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='columna',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='lote',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
