# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-02-27 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0015_cliente_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terreno',
            options={'ordering': ['manzana', 'columna', 'lote']},
        ),
    ]

