# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-11-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0018_auto_20211105_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='beneficiario_1',
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='beneficiario_2',
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True),
        ),
    ]
