# Generated by Django 4.1.3 on 2023-02-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0020_alter_cliente_id_alter_difunto_id_alter_terreno_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='lote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
