# Generated by Django 4.1.3 on 2023-02-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0021_alter_terreno_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mantenimiento',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
