# Generated by Django 4.1.3 on 2023-02-22 17:53

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0022_cliente_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terreno',
            options={'ordering': ['manzana', 'columna', django.db.models.functions.comparison.Cast('lote', output_field=models.IntegerField())]},
        ),
    ]
